import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#050505',
        surface: '#0A0A0A',
        'surface-container': '#121212',
        'surface-container-high': '#1A1A1A',
        'on-surface': '#FFFFFF',
        'on-surface-variant': '#A1A1AA',
        outline: '#3F3F46',
        'outline-variant': '#27272A',
        primary: '#3B82F6',
        'on-primary': '#FFFFFF',
        'primary-container': '#1D4ED8',
        'on-primary-container': '#DBEAFE',
        secondary: '#8B5CF6',
        'on-secondary': '#FFFFFF',
      },
      fontFamily: {
        "display-lg": ["var(--font-inter)", "sans-serif"],
        "display-md": ["var(--font-inter)", "sans-serif"],
        "display-sm": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "label-lg": ["var(--font-geist-sans)", "sans-serif"],
        "label-md": ["var(--font-geist-sans)", "sans-serif"],
        "label-sm": ["var(--font-geist-sans)", "sans-serif"],
        "code-md": ["var(--font-geist-mono)", "monospace"],
      },
      fontSize: {
        "display-lg": ["57px", "64px"],
        "display-md": ["45px", "52px"],
        "display-sm": ["36px", "44px"],
        "headline-lg": ["32px", "40px"],
        "headline-md": ["28px", "36px"],
        "headline-sm": ["24px", "32px"],
        "body-lg": ["16px", "24px"],
        "body-md": ["14px", "20px"],
        "body-sm": ["12px", "16px"],
        "label-lg": ["14px", "20px"],
        "label-md": ["12px", "16px"],
        "label-sm": ["11px", "16px"],
        "code-md": ["14px", "20px"],
      },
      spacing: {
        "gutter": "16px",
        "margin-desktop": "24px",
        "margin-mobile": "16px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
} satisfies Config;
